version: '3'
services:
  app:
    image: tobysmyki/shiftz
    container_name: shiftz
    ports:
      - "5000:5000"
    volumes:
      - sqlite_data:/app/instance
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development

volumes:
  sqlite_data:
    driver: local